### ISSUE TITLE
Issue #1: Backend Infrastructure Setup with Google Cloud Platform

### ISSUE THREAD

**Issue by prof-schacht** [prof-schacht/cleanquest-ios#1]
### Overview
Set up the complete backend infrastructure using Google Cloud services for scalable, cost-effective operation of CleanQuest.

### Google Cloud Services Architecture
```
┌─────────────────────────────────────────────────────────┐
│                    iOS App (SwiftUI)                     │
└────────────────────┬────────────────────────────────────┘
                     │
┌────────────────────▼────────────────────────────────────┐
│              Cloud Endpoints (API Gateway)               │
│         - Authentication, Rate Limiting, Monitoring      │
└────────────────────┬────────────────────────────────────┘
                     │
┌────────────────────▼────────────────────────────────────┐
│           Cloud Run (Serverless Backend)                 │
│      - REST API (Node.js/Python FastAPI)               │
│      - Auto-scaling, Pay-per-use                       │
└──┬─────────────────┬─────────────────┬─────────────────┘
   │                 │                 │
┌──▼──┐         ┌───▼───┐        ┌───▼────┐
│ GCS  │         │Vertex │        │Firestore│
│Storage│        │  AI   │        │Database │
└──────┘        └───────┘        └─────────┘
```

#### 1. Google Cloud Project Setup
- [ ] Create new GCP project
- [ ] Enable required APIs:
  - Vertex AI API
  - Cloud Run API
  - Cloud Storage API
  - Firestore API
  - Cloud Endpoints API
  - Identity Platform API

#### 2. Cloud Run Backend Service
```python
# main.py - FastAPI backend
from fastapi import FastAPI, UploadFile, File
from google.cloud import storage, firestore
import vertexai
from vertexai.vision_models import MultiModalEmbeddingModel, ImageTextModel

app = FastAPI()

@app.post("/api/analyze-room")
async def analyze_room(
    user_id: str,
    images: List[UploadFile],
    mode: str,
    time_limit: int,
    motivation: str
):
    # Upload images to GCS
    # Call Vertex AI for analysis
    # Generate task list
    # Store in Firestore
    # Return task list
    pass

@app.post("/api/complete-task")
async def complete_task(user_id: str, task_id: str):
    # Update task status
    # Calculate rewards
    # Update user stats
    pass
```

#### 3. Cloud Storage Setup
- [ ] Create buckets:
  - `cleanquest-user-images` (for room photos)
  - `cleanquest-temp-analysis` (for processing)
- [ ] Set lifecycle policies for auto-deletion after 30 days
- [ ] Configure signed URLs for secure uploads

#### 4. Firestore Database Schema
```javascript
// Collections structure
users/
  {userId}/
    profile: { totalSponges, level, streak }
    sessions/
      {sessionId}/
        photos: []
        tasks: []
        completedAt: timestamp

tasks/
  {taskId}/
    title: string
    subtasks: []
    estimatedTime: number
    spongeReward: number
```

#### 5. Vertex AI Configuration
- [ ] Set up Gemini 2.0 Flash model access
- [ ] Create custom prompts for room analysis
- [ ] Implement rate limiting and cost controls

#### 6. Authentication Setup
- [ ] Configure Google Identity Platform
- [ ] Set up Sign in with Apple for iOS
- [ ] Implement JWT token validation

### Cost Optimization Strategies
1. **Cloud Run**: Scales to zero when not in use
2. **Firestore**: Use batch operations, implement data retention policies
3. **Cloud Storage**: Lifecycle policies, use Nearline for older data
4. **Vertex AI**: Use Gemini Flash (cheaper), implement caching

### Environment Configuration
```yaml
# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cleanquest-backend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cleanquest-backend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'cleanquest-backend'
      - '--image=gcr.io/$PROJECT_ID/cleanquest-backend'
      - '--region=us-central1'
      - '--platform=managed'
```

### Acceptance Criteria
- [ ] Backend API deployed on Cloud Run
- [ ] All Google Cloud services configured and connected
- [ ] Authentication working with test users
- [ ] Basic API endpoints functional
- [ ] Monitoring and logging set up
- [ ] Cost alerts configured

### Resources
- [Cloud Run quickstart](https://cloud.google.com/run/docs/quickstarts)
- [Vertex AI pricing](https://cloud.google.com/vertex-ai/pricing)
- [Firestore best practices](https://firebase.google.com/docs/firestore/best-practices)
