### ISSUE TITLE
Issue #8: Testing, Deployment, and Monitoring

### ISSUE THREAD

**Issue by prof-schacht** [prof-schacht/cleanquest-ios#8]
### Overview
Implement comprehensive testing, CI/CD pipelines, App Store deployment, and production monitoring for both iOS app and backend services. This ensures quality, reliability, and maintainability of CleanQuest.

### Components
1. **Testing**: Unit, Integration, UI tests for iOS and API tests for backend
2. **CI/CD**: GitHub Actions for automated builds and deployments
3. **App Store**: Submission process and metadata
4. **Monitoring**: Error tracking, analytics, and performance monitoring
5. **A/B Testing**: Feature flags and experimentation

#### 1. iOS Testing Suite
```swift
// Tests/Unit/GamificationEngineTests.swift
import XCTest
@testable import CleanQuest

class GamificationEngineTests: XCTestCase {
    var engine: GamificationEngine!
    
    override func setUp() {
        super.setUp()
        engine = GamificationEngine()
    }
    
    func testSpongeAward() {
        // Given
        let initialSponges = engine.totalSponges
        let awardAmount = 50
        
        // When
        engine.awardSponges(awardAmount, reason: .taskCompletion(taskId: "test"))
        
        // Then
        XCTAssertEqual(engine.totalSponges, initialSponges + awardAmount)
    }
    
    func testLevelCalculation() {
        // Test level thresholds
        let testCases: [(sponges: Int, expectedLevel: Int)] = [
            (0, 1),
            (100, 2),
            (300, 3),
            (1500, 6)
        ]
        
        for testCase in testCases {
            engine.totalSponges = testCase.sponges
            engine.updateLevel()
            XCTAssertEqual(engine.currentLevel, testCase.expectedLevel)
        }
    }
}

// Tests/Integration/CloudServiceTests.swift
class CloudServiceIntegrationTests: XCTestCase {
    var cloudService: CloudService!
    
    override func setUp() async throws {
        try await super.setUp()
        cloudService = CloudService(baseURL: "https://test-api.cleanquest.app")
    }
    
    func testRoomAnalysis() async throws {
        // Given
        let testImages = [UIImage.testImage()]
        let parameters = AnalysisParameters(
            mode: .cleaning,
            timeLimit: 30,
            motivation: "High"
        )
        
        // When
        let result = try await cloudService.analyzeRoom(
            images: testImages,
            parameters: parameters
        )
        
        // Then
        XCTAssertFalse(result.tasks.isEmpty)
        XCTAssertGreaterThan(result.tasks.count, 0)
    }
}

// Tests/UI/CleaningFlowUITests.swift
import XCTest

class CleaningFlowUITests: XCTestCase {
    var app: XCUIApplication!
    
    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        app = XCUIApplication()
        app.launchArguments = ["--uitesting"]
        app.launch()
    }
    
    func testCompleteCleaningFlow() {
        // Camera Screen
        app.buttons["CaptureButton"].tap()
        sleep(1)
        app.buttons["CaptureButton"].tap()
        
        // Verify photos taken
        XCTAssertEqual(app.images.matching(identifier: "PhotoThumbnail").count, 2)
        
        // Proceed to review
        app.buttons["ReviewCheckmark"].tap()
        
        // Photo Review
        XCTAssertTrue(app.navigationBars["Photo Review"].exists)
        app.buttons["ProceedCheckmark"].tap()
        
        // Personalization
        app.buttons["CleaningModeButton"].tap()
        app.buttons["NextButton"].tap()
        
        // Time selection
        app.textFields["TimeInput"].tap()
        app.typeText("20")
        app.buttons["NextButton"].tap()
        
        // Motivation
        app.buttons["HighMotivationButton"].tap()
        app.buttons["StartButton"].tap()
        
        // Wait for task generation
        let taskList = app.scrollViews["TaskList"]
        XCTAssertTrue(taskList.waitForExistence(timeout: 10))
        
        // Start cleaning mode
        app.buttons["StartCleaningMode"].tap()
        
        // Complete first task
        let subtaskCheckbox = app.buttons.matching(identifier: "SubtaskCheckbox").firstMatch
        XCTAssertTrue(subtaskCheckbox.exists)
        subtaskCheckbox.tap()
    }
}
```

#### 2. Backend Testing
```python
# tests/test_api.py
import pytest
from fastapi.testclient import TestClient
from unittest.mock import patch, MagicMock

from main import app

client = TestClient(app)

class TestRoomAnalysis:
    @pytest.fixture
    def mock_vertex_ai(self):
        with patch('services.vertex_ai_service.GenerativeModel') as mock:
            yield mock
    
    @pytest.fixture
    def auth_headers(self):
        return {"Authorization": "Bearer test_token"}
    
    def test_analyze_room_success(self, mock_vertex_ai, auth_headers):
        # Mock AI response
        mock_vertex_ai.return_value.generate_content_async.return_value.text = '''
        {
            "room_assessment": {
                "cleanliness_level": "6",
                "main_issues": ["Cluttered surfaces", "Dusty shelves"]
            },
            "tasks": [
                {
                    "id": "task1",
                    "title": "Clear desk surface",
                    "subtasks": [
                        {"id": "sub1", "description": "Remove papers"}
                    ],
                    "estimated_time": 10,
                    "sponge_reward": 20
                }
            ],
            "encouragement": "Great job starting!"
        }
        '''
        
        response = client.post(
            "/api/analyze-room",
            json={
                "user_id": "test_user",
                "session_id": "test_session",
                "image_urls": ["https://example.com/image1.jpg"],
                "mode": "cleaning",
                "time_limit": 30,
                "motivation": "high"
            },
            headers=auth_headers
        )
        
        assert response.status_code == 200
        data = response.json()
        assert len(data["tasks"]) > 0
        assert data["tasks"][0]["title"] == "Clear desk surface"
    
    def test_analyze_room_invalid_mode(self, auth_headers):
        response = client.post(
            "/api/analyze-room",
            json={
                "mode": "invalid_mode",
                "time_limit": 30
            },
            headers=auth_headers
        )
        
        assert response.status_code == 422

# tests/test_gamification.py
class TestGamificationService:
    @pytest.fixture
    def gamification_service(self):
        return GamificationService()
    
    def test_level_calculation(self, gamification_service):
        test_cases = [
            (0, 1),
            (100, 2),
            (300, 3),
            (1500, 6)
        ]
        
        for sponges, expected_level in test_cases:
            level = gamification_service.calculate_level(sponges)
            assert level == expected_level
    
    @pytest.mark.asyncio
    async def test_streak_update(self, gamification_service):
        # Test consecutive day
        with freeze_time("2025-01-01"):
            streak = await gamification_service.update_streak("user1")
            assert streak == 1
        
        with freeze_time("2025-01-02"):
            streak = await gamification_service.update_streak("user1")
            assert streak == 2
        
        # Test broken streak
        with freeze_time("2025-01-04"):
            streak = await gamification_service.update_streak("user1")
            assert streak == 1
```

#### 3. CI/CD Pipeline
```yaml
# .github/workflows/ios-ci.yml
name: iOS CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Install Dependencies
      run: |
        brew install swiftlint
        pod install
    
    - name: Run SwiftLint
      run: swiftlint
    
    - name: Run Unit Tests
      run: |
        xcodebuild test \
          -workspace CleanQuest.xcworkspace \
          -scheme CleanQuest \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -resultBundlePath TestResults
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults.xcresult
  
  build:
    needs: test
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Certificates
      env:
        CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
        PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # Create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        
        # Import certificate
        echo "$CERTIFICATE_BASE64" | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
        
        # Install provisioning profile
        echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > profile.mobileprovision
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
    
    - name: Build Archive
      run: |
        xcodebuild archive \
          -workspace CleanQuest.xcworkspace \
          -scheme CleanQuest \
          -configuration Release \
          -archivePath $PWD/build/CleanQuest.xcarchive \
          -allowProvisioningUpdates
    
    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/CleanQuest.xcarchive \
          -exportPath $PWD/build \
          -exportOptionsPlist ExportOptions.plist
    
    - name: Upload to TestFlight
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      run: |
        xcrun altool --upload-app \
          -f build/CleanQuest.ipa \
          -t ios \
          --apiKey "$APP_STORE_CONNECT_API_KEY" \
          --apiIssuer "${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}"

# .github/workflows/backend-cd.yml
name: Backend CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build and Push
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cleanquest-backend:$GITHUB_SHA ./backend
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cleanquest-backend:$GITHUB_SHA
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy cleanquest-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cleanquest-backend:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
```

#### 4. App Store Configuration
```swift
// App Store Connect Metadata
struct AppStoreMetadata {
    static let appName = "CleanQuest - Gamified Room Cleaning"
    
    static let subtitle = "Make cleaning fun with AI-powered tasks"
    
    static let description = """
    Transform your cleaning routine into an exciting adventure with CleanQuest!
    
    🧹 SMART TASK GENERATION
    Simply take photos of your room, and our AI creates personalized cleaning tasks tailored to your space and available time.
    
    🎮 GAMIFICATION THAT MOTIVATES
    • Earn sponges for completing tasks
    • Level up and unlock achievements
    • Track your cleaning streaks
    • Compete with friends (coming soon!)
    
    ✨ KEY FEATURES
    • AI-powered room analysis using advanced vision technology
    • Customizable cleaning modes: Deep Clean, Standard, Organizing, or Quick Tidy
    • Time-based task optimization
    • Beautiful bubble animations and haptic feedback
    • Offline support for uninterrupted cleaning
    • Progress tracking and statistics
    
    🔒 PRIVACY FIRST
    • Your photos are processed securely and deleted after analysis
    • GDPR compliant with data export options
    • Optional anonymous mode
    • No ads, no tracking
    
    Whether you're tackling a messy bedroom, organizing your office, or doing a quick tidy before guests arrive, CleanQuest makes the process enjoyable and rewarding.
    
    Start your cleaning adventure today!
    """
    
    static let keywords = [
        "cleaning", "room cleaning", "gamification", "organization",
        "tidy", "chores", "productivity", "home", "tasks", "AI"
    ]
    
    static let screenshots = [
        "camera_capture.png",
        "task_generation.png",
        "cleaning_mode.png",
        "achievements.png",
        "profile_stats.png"
    ]
    
    static let privacyPolicyURL = "https://cleanquest.app/privacy"
    static let termsOfServiceURL = "https://cleanquest.app/terms"
}

// Info.plist additions
/*
<key>NSCameraUsageDescription</key>
<string>CleanQuest needs camera access to take photos of your room for AI-powered cleaning task generation.</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>CleanQuest can save before/after photos to your photo library to track your cleaning progress.</string>
*/
```

#### 5. Monitoring Setup
```swift
// Core/Monitoring/AnalyticsService.swift
import FirebaseAnalytics
import FirebaseCrashlytics

class AnalyticsService {
    static let shared = AnalyticsService()
    
    func trackEvent(_ event: AnalyticsEvent) {
        Analytics.logEvent(event.name, parameters: event.parameters)
    }
    
    func trackScreen(_ screen: String) {
        Analytics.logEvent(AnalyticsEventScreenView, parameters: [
            AnalyticsParameterScreenName: screen
        ])
    }
    
    func setUserProperties(_ properties: [String: Any]) {
        for (key, value) in properties {
            Analytics.setUserProperty("\(value)", forName: key)
        }
    }
}

enum AnalyticsEvent {
    case sessionStarted(mode: String, timeLimit: Int)
    case taskCompleted(taskId: String, timeSpent: Int)
    case sessionCompleted(totalSponges: Int, tasksCompleted: Int)
    case levelUp(newLevel: Int)
    case achievementUnlocked(achievementId: String)
    
    var name: String {
        switch self {
        case .sessionStarted: return "session_started"
        case .taskCompleted: return "task_completed"
        case .sessionCompleted: return "session_completed"
        case .levelUp: return "level_up"
        case .achievementUnlocked: return "achievement_unlocked"
        }
    }
    
    var parameters: [String: Any] {
        switch self {
        case .sessionStarted(let mode, let timeLimit):
            return ["mode": mode, "time_limit": timeLimit]
        case .taskCompleted(let taskId, let timeSpent):
            return ["task_id": taskId, "time_spent": timeSpent]
        case .sessionCompleted(let totalSponges, let tasksCompleted):
            return ["total_sponges": totalSponges, "tasks_completed": tasksCompleted]
        case .levelUp(let newLevel):
            return ["new_level": newLevel]
        case .achievementUnlocked(let achievementId):
            return ["achievement_id": achievementId]
        }
    }
}

// Error tracking
extension Crashlytics {
    static func track(error: Error, context: [String: Any]) {
        Crashlytics.crashlytics().record(error: error)
        
        for (key, value) in context {
            Crashlytics.crashlytics().setCustomValue(value, forKey: key)
        }
    }
}
```

#### 6. Performance Monitoring
```python
# backend/monitoring/metrics.py
from prometheus_client import Counter, Histogram, Gauge
import time
from functools import wraps

# Metrics
api_requests = Counter('api_requests_total', 'Total API requests', ['endpoint', 'method', 'status'])
api_latency = Histogram('api_request_duration_seconds', 'API request latency', ['endpoint'])
active_sessions = Gauge('active_cleaning_sessions', 'Number of active cleaning sessions')
vertex_ai_calls = Counter('vertex_ai_calls_total', 'Total Vertex AI API calls', ['status'])
vertex_ai_cost = Counter('vertex_ai_cost_dollars', 'Vertex AI API cost in dollars')

def track_request(endpoint: str):
    def decorator(func):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            start_time = time.time()
            status = "success"
            
            try:
                result = await func(*args, **kwargs)
                return result
            except Exception as e:
                status = "error"
                raise
            finally:
                duration = time.time() - start_time
                api_requests.labels(endpoint=endpoint, method="POST", status=status).inc()
                api_latency.labels(endpoint=endpoint).observe(duration)
        
        return wrapper
    return decorator

# Grafana Dashboard Configuration
dashboard_config = {
    "panels": [
        {
            "title": "API Request Rate",
            "query": "rate(api_requests_total[5m])"
        },
        {
            "title": "API Latency (p95)",
            "query": "histogram_quantile(0.95, rate(api_request_duration_seconds_bucket[5m]))"
        },
        {
            "title": "Active Sessions",
            "query": "active_cleaning_sessions"
        },
        {
            "title": "Vertex AI Cost",
            "query": "increase(vertex_ai_cost_dollars[1h])"
        }
    ]
}
```

### Acceptance Criteria
- [ ] Unit test coverage > 80%
- [ ] Integration tests for critical paths
- [ ] UI tests for main user flows
- [ ] CI/CD pipeline runs on every commit
- [ ] Automated deployment to TestFlight
- [ ] Backend deploys to Cloud Run automatically
- [ ] Monitoring dashboards configured
- [ ] Error tracking in place
- [ ] Performance metrics collected
- [ ] App Store submission ready

### Release Checklist
- [ ] Version number incremented
- [ ] Release notes written
- [ ] Screenshots updated
- [ ] App Store description current
- [ ] Privacy policy updated
- [ ] TestFlight beta tested
- [ ] Performance benchmarks met
- [ ] Security scan passed
- [ ] Accessibility tested
- [ ] Localization complete (if applicable)

### Post-Launch Monitoring
1. **Key Metrics to Track**
   - Daily Active Users (DAU)
   - Session completion rate
   - Average sponges per session
   - Crash-free rate
   - API response times
   - Vertex AI costs

2. **Alert Thresholds**
   - API error rate > 1%
   - Response time > 2s (p95)
   - Crash rate > 0.5%
   - Daily cost > $100

### Resources
- [XCTest Documentation](https://developer.apple.com/documentation/xctest)
- [GitHub Actions for iOS](https://docs.github.com/en/actions/deployment/deploying-xcode-applications)
- [App Store Connect API](https://developer.apple.com/documentation/appstoreconnectapi)
- [Firebase Monitoring](https://firebase.google.com/docs/perf-mon)
